### ISSUE TITLE
Slash commands not working 

### ISSUE THREAD

**Issue by rycerzes** [Xenorio/ScamAway#25]
![image](https://user-images.githubusercontent.com/59965507/154098852-e5dffa43-76af-4371-93f4-57902d9dd444.png)
![image](https://user-images.githubusercontent.com/59965507/154098983-be48c7ef-a23e-4d8f-9948-dedc522e1c4c.png)
I have enabled applications.command and bot perms too
Pls help

**Comment by xenorio** [comment]
Can you provide the invite link you're using? Are you absolutely sure it asks for permission to "Create commands in a server" when clicking it? The scope is "applications.commands", not "applications.command".

Also, please try using the auto-generated invite it spits into the terminal. Just implemented that, so you'll need to update for that.

**Comment by rycerzes** [comment]
Hey, thanks for responding! The new update which generates the bot invite link was much needed and it works perfectly!
Thanks!!
